---
booktitle: Proceedings of KDD Cup 2011
publisher: JMLR Workshop and Conference Proceedings
logoright: logo.jpg
volume: 18
year: '2011'
start: 2011-08-21
end: 2011-08-21
published: 2012-06-01
shortname: KDD Cup 2011
sections:
- name: introduction
  title: Introduction
- name: track1
  title: Track 1
- name: default
  title: Track 2
layout: proceedings
series: Proceedings of Machine Learning Research
id: DrorKDD2011
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: false
editor:
- given: Gideon
  family: Dror
- given: Yehuda
  family: Koren
- given: Markus
  family: Weimer
description: |
  Proceedings of KDD Cup 2011 on 21 August 2011

  Published as Volume 18 by the Proceedings of Machine Learning Research on 01 June 2012.

  Volume Edited by:
    Gideon Dror
    Yehuda Koren
    Markus Weimer

  Series Editors:
    Neil D. Lawrence
date_str: 21 Aug
url: http://proceedings.mlr.press
baseurl: "/v18"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v18
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Proceedings of KDD Cup 2011
  url: 
  location: 
  dates:
  - 2011-08-21
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v18.bib
